export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_AUTH_MODAL = 'SET_AUTH_MODAL';
export const SET_IS_AUTH = 'SET_IS_AUTH';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FIELD = 'SET_CURRENT_USER_FIELD';
export const SET_LOGGING_IN = 'SET_LOGGING_IN';
export const SET_SIGNING_UP = 'SET_SIGNING_UP';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const SET_AUTH_FORM_FIELD = 'SET_AUTH_FORM_FIELD';
export const CLEAR_AUTH_FORM = 'CLEAR_AUTH_FORM';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const SET_UPDATING_CURRENT_USER = 'SET_UPDATING_CURRENT_USER';
export const SET_UPDATING_CURRENT_USER_ADDRESS =
  'SET_UPDATING_CURRENT_USER_ADDRESS';
