export const SET_LOADING_ALL_ITEMS = 'SET_LOADING_ALL_ITEMS';
export const SET_LOADING_ITEMS = 'SET_LOADING_ITEMS';
export const SET_ALL_ITEMS = 'SET_ALL_ITEMS';
export const SET_ITEMS = 'SET_ITEMS';
