export const SET_SHIPPING_REGION = 'SET_SHIPPING_REGION';
export const SET_SHIPPING_REGIONS = 'SET_SHIPPING_REGIONS';
export const SET_LOADING_SHIPPING_REGION = 'SET_LOADING_SHIPPING_REGION';
export const SET_LOADING_SHIPPING_REGIONS = 'SET_LOADING_SHIPPING_REGIONS';
